### ISSUE TITLE
Intialize is not a function

### ISSUE THREAD

**Issue by IgordeOliveira** [moisesbaez/mautic-tracking#1]
`vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "TypeError: mautic_tracking__WEBPACK_IMPORTED_MODULE_0___default.a.intialize is not a function"`

**Comment by IgordeOliveira** [comment]
mautic.intialize('https://my.mautic-installation.com/mtc.js');
documentation has typo
initialize

**Comment by moisesbaez** [comment]
Made the fix on the README. Thanks!
