### ISSUE TITLE
mautic-tracker accumulates each page view click by click

### ISSUE THREAD

**Issue by Florian79** [moisesbaez/mautic-tracking#17]
hey Moises Baez,

i am trying to integrate mautic tracking into my nextjs app and luckily i found your code here on github!

but unfortunately it accumulates each page view click by click. so the first page view gets tracked once (correctly) the second twice, the third three times and so on..

my code as follows (googleGA tracks correctly with this set up) :

```

import AnalyticsGA from "react-ga4";
import AnalyticsMautic from 'mautic-tracking';

const App = ({ Component, pageProps }) => {
    useEffect(() => {
        if(process.env.NODE_ENV === "production") { // Checks for GA ID and only turns on GA in production
            AnalyticsGA.initialize(process.env.GOOGLE_ANALYTICS||'G-XXX');
            AnalyticsGA.send("pageview");

            AnalyticsMautic.initialize(process.env.MAUTIC_ANALYTICS||'https://xxx.com/mtc.js');
            AnalyticsMautic.pageView({ custom: 'options' });
        }
    });
  return (
    <Layout {...pageProps}>
      <Component {...pageProps} />
      {/*more stuff here*/}
    </Layout>
  )
}
```

some advise is highly appreciated!

thanks,
florian

**Comment by moisesbaez** [comment]
Hi @Florian79 . I think you need to apply an empty array as your second argument to your `useEffect`. The way your code is currently laid out, the effect will continuously fire every time the component updates. From what I can see, I believe you only want to fire these page views on the initial load. That would mean your use effect should look like this:

```js
    useEffect(() => {
      // your code goes here...
    }, []);  // empty array so it doesn't contiuously fire
```

Hope this resolves your issue!
