### ISSUE TITLE
example of all page tracking

### ISSUE THREAD

**Issue by KotskinKotskin** [moisesbaez/mautic-tracking#3]
Hi!. Can you provide example for every page visit tracking?

**Comment by moisesbaez** [comment]
If you're using something like `react-router` then what you can do is use `createBrowserHistory` to create a history which will listen for route changes . From there you can then fire a page view on the history listener.

```js
import { Router } from 'react-router-dom';
import { createBrowserHistory } from 'history';
import mautic from 'mautic-tracking';

mautic.initialize('https://my.mautic-installation.com/mtc.js');
const history = createBrowserHistory();

const historyListener = (location) => {
  mautic.pageView();
};

history.listen(historyListener);
historyListener(window.location);

return (
  <Router history={history}>
    <App />
  </Router>
);
```

Alternatively you can just import `mautic` and fire a `pageView` on each route component. Just make sure that you've initialized the mautic module before you start sending a page view.

**Comment by KotskinKotskin** [comment]
Great, thanks. I will post here vue example

**Comment by KotskinKotskin** [comment]
router.beforeEach((to, from, next) => {
  mautic.pageView(window.location);
  next();
})

work for me
